### PR TITLE
Add pause control

### PR DESCRIPTION
**Pull request by curlydingo**
Adds pause control per request in #74. Seems to work successfully on my instance.

Next step is to add to hass-opensprinkler but one thing at a time.

### CODE REVIEW

**Review by vinteo — APPROVED** [review]

**Comment by vinteo** [comment]
Just as a reference why the test runner is not running; https://github.com/vinteo/py-opensprinkler/issues/90

**Comment by EdLeckert** [comment]
@curlydingo I see you chose 2**32 as a maximum value by examining the code. It's unfortunate that the API doc doesn't mention a maximum, but I did find two implied maximum values in the UI. 

The feature to `Pause Station Runs`  will not allow a value of greater than 18:12:15, or (2**16)-1 when using the `+` buttons, though you can type in a much higher value. It's possible this is an oversight, say an accidental reuse of the limit on program duration.

Then the display in the footer will not display more than 24 hours, though when it counts down to zero, it picks up again if there is time remaining. Any time greater than a day cannot be seen by the user.

So I would propose, given the potential confusion caused by the footer's inability to display more then 24 hours, that we limit the maximum to 24 hours, unless the UI is changed in the future. Of course this could be limited in the hass piece instead, leaving it a longword here.

Thoughts?

**Comment by curlydingo** [comment]
Yes, I agree. In the absence of a specified API limit, limiting it to when we know that the UI will start misbehaving makes sense.

**Review by EdLeckert — APPROVED** [review]

**Comment by vinteo** [comment]
thanks @curlydingo

**Pull request merged**
