### PR TITLE
better naming for stop/reset stations

### PR DESCRIPTION
**Pull request by travisghansen**

### CODE REVIEW

**Comment by vinteo** [comment]
I don't think we need to add the extra method. I will just use the `stop_all_stations` method in the integration PR

**Comment by travisghansen** [comment]
Meaning you want to remove it from the PR?

**Comment by vinteo** [comment]
I think we can close this PR, I prefer the `stop_all_stations` name actually, what do you think?

**Comment by travisghansen** [comment]
@vinteo this is doing 2 things, it's adding a method which didn't exist previously and renaming the other. I think it's decent convenience method to do the iteration bit without canceling the `waiting` but I don't have much opinion on the naming.

**Comment by vinteo** [comment]
Like i said before there might not be any use for that method if there is the "reset" one. I think they is a reason why OS only provides the "reset" function

**Comment by travisghansen** [comment]
OK, shut it down.

**Pull request closed without merging**
