### PR TITLE
fix-aiohttp-requirement

### PR DESCRIPTION
**Pull request by EdLeckert**
To fix hass-opensprinkler OpenSprinkler not working since update to HA2023.10.2 #259

### CODE REVIEW

**Comment by vinteo** [comment]
I am a bit conflicted about `>=` but maybe we should just do it. Can you resolve the conflict and I will merge it

**Comment by EdLeckert** [comment]
I hear ya', but I can't see how letting it break with every other release of HA helps anyone.

Let me look into how one does that. <Sigh>

**Comment by EdLeckert** [comment]
Obviously I hadn't noticed that you had already made the change. Sorry about that.

**Review by vinteo — APPROVED** [review]

**Comment by EdLeckert** [comment]
@vinteo  Have you seen this?:

### Release 2023.10.3 - October 13

- Downgrade aiohttp to 3.8.5 ([@frenck](https://github.com/frenck) - [#101913](https://github.com/home-assistant/core/pull/101913))

**Comment by vinteo** [comment]
No... Well people can downgrade the integration too lol.

I don't get the dependency management system here coming from node.js

**Comment by vinteo** [comment]
Should we do a release as well? We have the >= now and can go with 3.8.5

**Comment by EdLeckert** [comment]
I think we're fine as is. I was just pointing out what could have happened with the back and forth in HA.

**Pull request merged**
